Document: python-synapse
Title: Debian python-synapse Manual
Author: <insert document author here>
Abstract: This manual describes what python-synapse is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-synapse/python-synapse.sgml.gz

Format: postscript
Files: /usr/share/doc/python-synapse/python-synapse.ps.gz

Format: text
Files: /usr/share/doc/python-synapse/python-synapse.text.gz

Format: HTML
Index: /usr/share/doc/python-synapse/html/index.html
Files: /usr/share/doc/python-synapse/html/*.html
